#!/bin/bash
#Author - Jakeer
#Team - DevOps
SOURCE_DIR="/home/ec2-user/logs"
R="\e[31m"
G="\e[32m"
N="\e[0m"
Y="\e[33m"

if [ -d $SOURCE_DIR ];then
echo -e " $SOURCE_DIR $G is available $N "
else
echo -e " $SOURCE_DIR $G is not available $N "
exit 1
fi
files=$(-name "*.log" -mtime +14 -exec ls -ltr)
echo $files